from __future__ import annotations


REGISTERED_SLASH_TOKENS: frozenset[str] = frozenset({"help", "toolbox", "isaac", "i叔", "艾萨克", "confirm", "token"})

TOOL_ALIASES: dict[str, str] = {
    "status": "status",
    "状态": "status",
    "help": "status",
    "工具箱": "status",
    "list": "list",
    "ls": "list",
    "dir": "list",
    "目录": "list",
    "列目录": "list",
    "read": "read",
    "cat": "read",
    "读取": "read",
    "读": "read",
    "看": "read",
    "log": "log_tail",
    "logs": "log_tail",
    "tail": "log_tail",
    "log_tail": "log_tail",
    "日志": "log_tail",
    "python": "python",
    "py": "python",
    "shell": "shell",
    "sh": "shell",
    "cmd": "shell",
    "命令": "shell",
    "write": "write",
    "写": "write",
    "写入": "write",
    "append": "write",
    "追加": "write",
    "pack": "pack",
    "tar": "pack",
    "archive": "pack",
    "打包": "pack",
    "压缩": "pack",
    "list_model_profiles": "list_model_profiles",
    "get_active_model_profile": "get_active_model_profile",
    "set_active_model_profile": "set_active_model_profile",
    "set_model_profile_enabled": "set_model_profile_enabled",
    "enable_model_profile": "set_model_profile_enabled",
    "启用模型": "set_model_profile_enabled",
    "禁用模型": "set_model_profile_enabled",
    "test_model_profile": "test_model_profile",
    "refresh_model_profiles": "refresh_model_profiles",
    "刷新模型": "refresh_model_profiles",
    "刷新模型列表": "refresh_model_profiles",
    "拉取模型列表": "refresh_model_profiles",
    "模型列表": "list_model_profiles",
    "当前模型": "get_active_model_profile",
    "切模型": "set_active_model_profile",
    "启用模型": "set_model_profile_enabled",
    "禁用模型": "set_model_profile_enabled",
    "测试模型": "test_model_profile",
    "token": "query_token_usage",
    "tokens": "query_token_usage",
    "query_token_usage": "query_token_usage",
    "查询token": "query_token_usage",
    "查token": "query_token_usage",
    "token用量": "query_token_usage",
}
AVAILABLE_TOOLS: tuple[str, ...] = (
    "status",
    "list",
    "read",
    "log_tail",
    "python",
    "shell",
    "write",
    "pack",
    "get_tool_loop_max_steps",
    "set_tool_loop_max_steps",
    "list_model_profiles",
    "get_active_model_profile",
    "set_active_model_profile",
    "set_model_profile_enabled",
    "test_model_profile",
    "refresh_model_profiles",
    "query_token_usage",
    "isaac_p0",
)
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_MAX_OUTPUT_CHARS = 8000
DEFAULT_MAX_READ_BYTES = 256 * 1024
DEFAULT_MAX_LIST_ENTRIES = 200
DEFAULT_MAX_PACK_FILES = 2000
